### ISSUE TITLE
Enter Key to Submit Hero Selection

### ISSUE THREAD

**Issue by XariZaru** [AndrisBorbas/smitedle#1]
**Is your feature request related to a problem? Please describe.**
it's quite annoying to not be able to type your hero in and hit enter to select them! I have to click. It's extra UX steps.

**Describe the solution you'd like**
Enter should submit.

**Describe alternatives you've considered**
There are no alternatives.

**Additional context**

Thank you

**Comment by AndrisBorbas** [comment]
I added it, let me know if anythings wrong.
