### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by WapsRodiah** [AndrisBorbas/smitedle#2]
Hello just to say that the ability on 08/21
/24 is wrong you put wukong 3 and the answer was erlang

**Comment by AndrisBorbas** [comment]
Well sorry, but that is on HiRez 😅
https://www.smitegame.com/gods/erlang-shen
https://www.smitegame.com/gods/sun-wukong
The abilities have the same name and icon on the website and i get the data from the same api.

They store the icons for the abilities by name and the abilites have the same name.
